### ISSUE TITLE
translation_fallback not working

### ISSUE THREAD

**Issue by lukepass** [sonata-project/SonataTranslationBundle#218]
I am using Sonata Translation with Gedmo and it's working fine. This is my configuration:

```
# Doctrine Extensions Configuration
stof_doctrine_extensions:
    default_locale: '%locale%'
    translation_fallback: true
    orm:
        default:
            timestampable: true
            blameable: true
            translatable: true

# Sonata Translation Configuration
sonata_translation:
    locales: [en, fr, it]
    default_locale: '%locale%'
    gedmo:
        enabled: true

## Sonata Admin Configuration
sonata_admin:
    templates:
        layout: admin/standard_layout.html.twig
```

However `translation_fallback` it's **not working**. Putting a breakpoint here:

vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/TranslatableListener.php
```
    public function setTranslationFallback($bool)
    {
        $this->translationFallback = (bool) $bool;

        return $this;
    }
```

The value is correctly set to `true` but when the value is requested by:

vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/TranslatableListener.php:
```
                // update translation
                if ($is_translated
                    || (!$this->translationFallback && (!isset($config['fallback'][$field]) || !$config['fallback'][$field]))
                    || ($this->translationFallback && isset($config['fallback'][$field]) && !$config['fallback'][$field])
                ) {
                    $ea->setTranslationValue($object, $field, $translated);
                    // ensure clean changeset
                    $ea->setOriginalObjectProperty(
                        $om->getUnitOfWork(),
                        $oid,
                        $field,
                        $meta->getReflectionProperty($field)->getValue($object)
                    );
                }
```

The value is `false`!
I put another breakpoint and I found that the culprit is here:

vendor/sonata-project/translation-bundle/Admin/Extension/Gedmo/TranslatableAdminExtension.php:
```
    /**
     * {@inheritdoc}
     */
    public function alterObject(AdminInterface $admin, $object)
    {
        if ($this->getTranslatableChecker()->isTranslatable($object)) {
            $translatableListener = $this->getTranslatableListener($admin);
            $translatableListener->setTranslatableLocale($this->getTranslatableLocale($admin));
            $translatableListener->setTranslationFallback(false); // <--- HERE

            $this->getContainer($admin)->get('doctrine')->getManager()->refresh($object);
            $object->setLocale($this->getTranslatableLocale($admin));
        }
    }
```

Why is it setting it to false? Am I missing something? Is it a service priority problem?

Thanks.
